# Generated by Django 5.0.3 on 2024-03-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_reactmodel_react'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='email',
            field=models.CharField(default='emailMissing', max_length=100),
            preserve_default=False,
        ),
    ]
